iterations: 1
max_num_epochs: 150
optimizer: adamw
weight_decay: 0.001
learning_rate: 00005
hidden_dim: 256
embedding_dim: 32
num_heads: 2
vocab_size: 2000
use_layer_norm: True
dropout: 0.3
rnn_state_dropout: 0.1
attn_dropout: 0.3
use_image_features: resnet_fourth_layer
img_feature_dropout: 0.0
junction_type_embedding: True
heading_change: True
heading_change_noise: 0.1
second_rnn: True
do_sample_bpe: True
use_text_attention: True
use_image_attention: True